services:
  - type: web
    name: dulpromax-backend
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install --no-cache-dir -r requirements.txt
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16  # Versión más estable en Render
      - key: ENVIRONMENT
        value: production
      - key: APP_VERSION
        value: 1.0.0
      - key: PIP_NO_CACHE_DIR
        value: "true"
